version: '3.3'

services:
  api: 
    build: .
    command: >
      sh -c "npm install &&
      npx nodemon app.ts"
    ports:
    - 3000:3000
    - 27017:27017
    # TODO: Review how to connect node to mongo without network host
    network_mode: host
    restart: always
  db:
    image: mongo:4.2.8
    restart: always
    ports: 
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: example
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: example