version: '3.3'

services:
  db:
    image: mongo:4.2.8
    restart: always
    network_mode: host
    environment:
      MONGO_INITDB_ROOT_USERNAME: example
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: example