version: '3.3'

services:
  api: 
    build: .
    command: >
      sh -c "npm install &&
      npx nodemon app.ts"
    network_mode: host # TODO: Review how to connect node to mongo without network host
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: mongo:4.2.8
    restart: unless-stopped
    ports: 
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: example
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: example
